api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('allphotoform-datas/', views.AllPhotoFormData.as_view()),
    path('mine/<int:pk>', views.MineDetailData.as_view())
]

rock/urls.py
from django.urls import path
from rock import views

app_name = 'rock'

urlpatterns = [
    path('', views.index, name='index'),
    path('upload_images/', views.FileFieldFormView.as_view(), name='upload_images'),
    path('rock/<int:pk>', views.RockSectionDetailView.as_view(), name='rock_detail'),
    path('mine/<int:pk>', views.MineDetailView.as_view(), name='mine_detail'),
    path('all_photos/', views.AllPhtotsView.as_view(), name='all_photos'),
]

rock_thin_section/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include


urlpatterns = [
    path('', include('rock.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include('api.urls'))
    # static(settings.STATIC_URL, document_root=settings.STATIC_ROOT),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rock/forms.py
from django import forms
from .models import PicInfo


class FileFieldForm(forms.Form):
    file_field = forms.FileField(
        widget=forms.ClearableFileInput(attrs={'multiple': True}))


class NormalSerchForm(forms.Form):
    search_field = forms.CharField(max_length=100, label=False, widget=forms.TextInput(
        attrs={'class': 'form-control mb-2', 'placeholder': '功能开发中', 'disabled': True}))


class DetailedSearchForm(forms.Form):
    ORTH_CHOICE = (('', '———'),) + PicInfo.ORTH_MODE

    region_field = forms.CharField(max_length=30, label='地区', required=False, widget=forms.TextInput(
        attrs={'class': 'form-control form-control-sm'}))
    mine_field = forms.CharField(max_length=50, label='井号', required=False, widget=forms.TextInput(
        attrs={'class': 'form-control form-control-sm'}))
    # depth_field = forms.FloatField(label='井深', required=False, widget=forms.TextInput(
    #     attrs={'class': 'form-control form-control-sm'}))
    depth_field = forms.FloatField(label='井深', required=False, widget=forms.NumberInput(
        attrs={'class': 'form-control'}))
    lens_field = forms.IntegerField(
        label='物镜倍数', required=False, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    orth_field = forms.ChoiceField(
        label='正交偏光', required=False, choices=ORTH_CHOICE, widget=forms.Select(attrs={'class': 'form-select form-select-sm'}))


class AllPhotosSearchForm(forms.Form):
    mines_selected = forms.CharField(
        required=True, widget=forms.TextInput(attrs={'hidden': True}))
    depth_low = forms.FloatField(
        required=False, widget=forms.NumberInput(attrs={'class': 'form-control', 'min': 0, 'max': 1000, 'required': True}))
    depth_high = forms.FloatField(
        required=False, widget=forms.NumberInput(attrs={'class': 'form-control', 'min': 0, 'max': 1000, 'required': True, 'disabled': True}))
    lens_selected = forms.CharField(
        required=True, widget=forms.TextInput(attrs={'hidden': True}))
    orths_selected = forms.CharField(
        required=True, widget=forms.TextInput(attrs={'hidden': True}))

rock/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from django.core.paginator import Paginator
from django.db.models import QuerySet
from django.views.generic.edit import FormView
from django.views import generic, View
from django.shortcuts import render
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from .forms import FileFieldForm, NormalSerchForm, DetailedSearchForm, AllPhotosSearchForm
from .models import PicInfo, Mine, Region
from fuzzywuzzy import fuzz, process

minimum_match_ratio = 50
depth_query_tolerance = 5
lens_query_tolerance = 1

pics_per_page = 12


class NameRepeatError(Exception):
    pass


# 基于类的视图验证superuser权限
class SuperUserRequiredMixin(LoginRequiredMixin, UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_superuser


def index(request):
    pic_list = []
    form_type = 'detailed_form'
    query_url_preffix = request.path

    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1

    if 'form_type' in request.GET:
        query_url_preffix = request.META['QUERY_STRING'].split('&page=')[0]
        form_type = request.GET['form_type']
        pics_all = PicInfo.objects.all()

        if form_type == 'normal_form':
            # normal_form = NormalSerchForm(request.GET)
            # detailed_form = DetailedSearchForm()
            # if normal_form.is_valid():
            #     search = normal_form.cleaned_data['search_field']
            #     picinfos = process.extract(
            #         search, pics_dic, scorer=fuzz.token_set_ratio)
            #     for pic in picinfos:
            #         id = pic[2]
            #         pic_inst = PicInfo.objects.get(pk=id)
            #         pic_list.append(pic_inst)
            pass

        elif form_type == 'detailed_form':
            normal_form = NormalSerchForm()
            detailed_form = DetailedSearchForm(request.GET)

            if detailed_form.is_valid():
                pics_queryset = pics_all

                if pics_queryset.exists() and (depth := detailed_form.cleaned_data['depth_field']):
                    if pics_queryset.filter(depth=depth).exists():
                        pics_queryset = pics_queryset.filter(depth=depth)
                    else:
                        pics_queryset = pics_queryset.filter(depth__range=(
                            depth-depth_query_tolerance, depth+depth_query_tolerance))

                if pics_queryset.exists() and (lens := detailed_form.cleaned_data['lens_field']):
                    if pics_queryset.filter(lens_mul=lens).exists():
                        pics_queryset = pics_queryset.filter(lens_mul=lens)
                    else:
                        pics_queryset = pics_queryset.filter(lens_mul__range=(
                            lens-lens_query_tolerance, lens+lens_query_tolerance))

                if pics_queryset.exists() and (orth := detailed_form.cleaned_data['orth_field']):
                    pics_queryset = pics_queryset.filter(orth=orth)

                # messages.info(request, str(pics_queryset))

                # 对地区和井号字段进行模糊搜索
                if pics_queryset.exists():
                    abstract_list = []
                    if region_name := detailed_form.cleaned_data['region_field']:
                        abstract_list.append(region_name)

                    if mine_name := detailed_form.cleaned_data['mine_field']:
                        abstract_list.append(mine_name)

                    # if depth := detailed_form.cleaned_data['depth_field']:
                    #     abstract_list.append('{:g}'.format(depth) + 'm')

                    # if lens := detailed_form.cleaned_data['lens_field']:
                    #     abstract_list.append(str(lens) + 'X')

                    # if orth := detailed_form.cleaned_data['orth_field']:
                    #     abstract_list.append(dict(PicInfo.ORTH_MODE).get(orth))

                    if abstract_list:
                        abstract_str = ' '.join(abstract_list)

                        pics_dic = {}
                        for pic in pics_queryset:
                            pics_dic[pic.id] = pic.get_clean_name(
                                PicInfo.PARTIAL_FIELDS)

                        all_ratios = process.extract(
                            abstract_str, pics_dic, scorer=fuzz.token_set_ratio, limit=10000)
                        highest_ratio = all_ratios[0][1]
                        # messages.info(request, 'highest ratio:' +
                        #               str(highest_ratio))

                        if highest_ratio >= minimum_match_ratio:
                            picinfos = [
                                ratio for ratio in all_ratios if ratio[1] == highest_ratio]
                            pics_queryset = pics_queryset.filter(
                                pk__in=[pic[2] for pic in picinfos])
                        else:
                            pics_queryset = []

                pics_pages_obj = Paginator(pics_queryset, pics_per_page)
                pics_page_obj = pics_pages_obj.get_page(page_num)

        return render(request, 'index.html', {'pics': pics_page_obj, 'normal_form': normal_form, 'detailed_form': detailed_form, 'form_type': form_type, 'query_url_preffix': query_url_preffix})

    else:
        normal_form = NormalSerchForm()
        detailed_form = DetailedSearchForm()
        pic_list = PicInfo.objects.all()
        pics_pages_obj = Paginator(pic_list, pics_per_page)
        pics_page_obj = pics_pages_obj.get_page(page_num)

        return render(request, 'index.html', {'pics': pics_page_obj, 'normal_form': normal_form, 'detailed_form': detailed_form, 'form_type': form_type})


class FileFieldFormView(SuperUserRequiredMixin, FormView):
    form_class = FileFieldForm
    template_name = 'upload_images.html'
    success_url = reverse_lazy('rock:upload_images')

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        files = request.FILES.getlist('file_field')

        error_files_num = 0
        successful_files_num = 0
        if form.is_valid():
            for f in files:
                try:
                    img_infos = f.name.split('-')
                    region = Region.objects.get(name=img_infos[0])
                    mine = Mine.objects.get(name=img_infos[1])
                    lens = int(img_infos[-3][:-1])
                    if img_infos[-2] == '正交':
                        orth = 'o'
                    elif img_infos[-2] == '单偏':
                        orth = 'p'
                    else:
                        raise ValueError
                    pic_num = int(img_infos[-1].split('.')[0])
                    if len(img_infos) == 6:
                        depth = float(img_infos[2][:-1])
                        if PicInfo.objects.filter(mine_num=mine, depth=depth, lens_mul=lens, orth=orth, pic_num=pic_num, remarks__isnull=True).exists():
                            raise NameRepeatError
                        picInfo_instance = PicInfo(
                            mine_num=mine, depth=depth, lens_mul=lens, orth=orth, pic_num=pic_num, image=f)
                    elif len(img_infos) == 7:
                        if img_infos[2].endswith('m'):
                            depth = float(img_infos[2][:-1])
                            remarks = int(img_infos[3])
                        elif img_infos[3].endswith('m'):
                            depth = float(img_infos[2])
                            remarks = int(img_infos[3][:-1])
                        if PicInfo.objects.filter(mine_num=mine, depth=depth, lens_mul=lens, orth=orth, pic_num=pic_num, remarks=remarks).exists():
                            raise NameRepeatError
                        picInfo_instance = PicInfo(
                            mine_num=mine, depth=depth, lens_mul=lens, orth=orth, pic_num=pic_num, image=f, remarks=remarks)
                    else:
                        raise ValueError
                    picInfo_instance.save()
                    successful_files_num = successful_files_num + 1
                except NameRepeatError:
                    messages.error(request, f'\'%s\'文件重复，无法导入。' % f.name)
                    error_files_num = error_files_num + 1
                except BaseException:
                    messages.error(request, f'\'%s\'文件命名不正确，无法导入。' % f.name)
                    error_files_num = error_files_num + 1
            messages.info(request, f'共选择%d个文件，成功导入%d个，失败%d个。' %
                          (len(files), successful_files_num, error_files_num))
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class RockSectionDetailView(generic.DetailView):
    model = PicInfo
    template_name = 'rock_detail.html'
    context_object_name = 'pic'


class MineDetailView(generic.DeleteView):
    model = Mine
    template_name = 'mine_detail.html'
    context_object_name = 'mine'


class AllPhtotsView(View):
    def render_form(self, search_form=None):
        regions = Region.objects.all()
        mines = Mine.objects.all()
        pics = PicInfo.objects.all()
        if not search_form:
            search_form = AllPhotosSearchForm()
        content = {
            'regions_all': regions,
            'mines_all': mines,
            'photos_all': pics,
            'lens_all': PicInfo.LENS_MUL,
            'orth_all': PicInfo.ORTH_MODE,
            'search_form': search_form,
        }

        return content

    def get(self, request, *args, **kwargs):
        content = self.render_form()

        # 获得页号
        page_num = 1
        if 'page' in request.GET:
            page_num = request.GET['page']

        pics_qs = PicInfo.objects.all()
        pics_pages_obj = Paginator(pics_qs, pics_per_page)

rock/templates/all_photos.html
{% extends "base_generic.html" %}

{% block static %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/all_photos.css' %}">
{% endblock %}

{% block title %}全部照片{% endblock %}

{% block content %}
<!-- Wrapper -->
<div class="wrapper">

    <!-- Sidebar -->
    <div class="flex-shrink-0 p-3 bg-white" id="sidebar">
        <!-- close sidebar menu -->
        <div
            class="d-flex align-items-center justify-content-between pb-3 mb-3 link-dark text-decoration-none border-bottom">
            <span class="fs-5 fw-semibold">筛选薄片</span>
            <div class="dismiss" id="dismiss">
                <i class="fas fa-arrow-left"></i>
            </div>
        </div>
        <div class="container-fluid px-0" hidden>
            <div class="alert alert-danger d-flex align-items-center p-2" id="alert_div" role="alert"></div>
        </div>
        <!-- <form method="post">
            {{ search_form }}
            <button type="submit">submit</button>
        </form> -->
        <div id="root"></div>
    </div>
    <!-- End sidebar -->

    <!-- Dark overlay -->
    <div class="" id="overlay"></div>

    <!-- Content -->
    <div class="content">

        <!-- open sidebar menu -->
        <div class="container-fluid">
            <div class="row"
                style="border-bottom-style: solid; border-color: rgb(202, 202, 202); background-color: rgb(235, 235, 235);">
                <div class="col-auto px-0">
                    <button class="btn btn-outline-success me-0" id="open-menu" type="button"
                        style="border-radius: 0; border-style: none; border-right-style: solid; padding: 8px;">
                        筛选薄片
                    </button>
                </div>
                <div class="col d-flex align-items-center justify-content-center px-0">
                    <p class="fw-semibold m-0 fs-5" style="color:rgb(87, 87, 87)">
                        {% if is_search %}
                        共搜索到{{ pics.paginator.count }}个结果
                        {% else %}
                        全部照片
                        {% endif %}
                    </p>
                </div>
            </div>
        </div>
        <!-- {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                {% endfor %}
        </ul>
        {% endif %} -->
        <!-- <div style="height: 10000px;"></div> -->

        <div class="album py-4 mt-3">
            <div class="container">

                <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                    {% for pic in pics %}
                    <div class="col">
                        <div class="card shadow-sm">
                            <img src="{{ pic.image.url }}">
                            <div class="card-body">
                                <p class="card-text text_center">{{ pic }}</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <button type="button" class="btn btn-sm btn-outline-secondary"
                                            onclick="window.location.href='{{ pic.get_absolute_url }}'">
                                            详情
                                        </button>
                                        <!-- <button type="button" class="btn btn-sm btn-outline-secondary">编辑</button> -->
                                    </div>
                                    <!-- <small class="text-muted">9 mins</small> -->
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% if pics.has_other_pages %}
            <nav class="mt-4">
                <ul class="pagination justify-content-center">
                    {% if not pics.has_previous %}
                    <li class="page-item disabled">
                        <a class="page-link">&laquo</a>
                    </li>
                    {% else %}
                    <li><a class="page-link" href="?page={{ pics.previous_page_number }}">
                            &laquo
                        </a></li>
                    {% endif %}
                    <li class="page-item"><a class="page-link">{{ pics.number }} of {{ pics.paginator.num_pages }}</a>
                    </li>
                    {% if not pics.has_next %}
                    <li class="page-item disabled">
                        <a class="page-link">&raquo</a>
                    </li>
                    {% else %}
                    <li><a class="page-link" href="?page={{ pics.next_page_number }}">
                            &raquo
                        </a></li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>

    </div>
    <!-- End content -->

</div>
<!-- End wrapper -->
{% endblock %}

{% block script %}
<script>
    window.csrf_token = '{{ csrf_token }}';
</script>
<script src="https://kit.fontawesome.com/2eddecd697.js" crossorigin="anonymous"></script>
<script src="{% static 'frontend/main.js' %}"></script>
<script src="{% static 'js/all_photos.js' %}"></script>
<!-- <script>
    function submitform() {
        mine_selected = document.getElementsByName('is_all_regions')[0];
        if (mine_selected.checked) {

        } else {
            mines_selected = mine_selected.querySelectorAll('[name="mines_selected"]');
            // alert(len(mines_selected));
        }
        alert('fesfes');
    }
</script> -->
{% endblock%}

rock/templates/base_generic.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="icon" href="{% static 'icon/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'bootstrap_custom/css/bootstrap_custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% block static %}{% endblock %}
    <title>{% block title %}{% endblock %}·西部岩石薄片检索系统</title>
</head>

<body>
    <header>
        <div class="collapse bg-dark" id="navbarHeader">
            <div class="container">
                <div class="row">
                    <div class="col-sm-8 col-md-7 py-4">
                        <h4 class="text-white">关于</h4>
                        <p class="text-muted">balabalabalabalabalabalabala</p>
                    </div>
                    <div class="col-sm-4 offset-md-1 py-4">
                        <h4 class="text-white">Contact</h4>
                        <ul class="list-unstyled">
                            {% if user.is_authenticated %}
                            <li><a href="{% url 'logout' %}" class="text-white">登出</a></li>
                            {% else %}
                            <!-- <li><a href="{% url 'login' %}" class="text-white">登录</a></li> -->
                            <li><a href="#" class="text-white">登录</a></li>
                            <!-- <li><a href="{% url 'logout' %}" class="text-white">注册</a></li> -->
                            <li><a href="#" class="text-white">注册</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="navbar navbar-dark bg-dark shadow-sm">
            <div class="container">
                <a href="#" class="navbar-brand d-flex align-items-center">
                    <!-- <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                        stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
                        viewBox="0 0 24 24">
                        <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z" />
                        <circle cx="12" cy="13" r="4" />
                    </svg> -->
                    <img src="{% static 'img/icon.png' %}" style="height: 40px;"><strong>西部岩石薄片检索系统</strong>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </div>
    </header>
    {% block content %}{% endblock %}

    <footer>
        <div class="container">
            <footer class="py-3 my-2">
                <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                    <li class="nav-item"><a href="{% url 'rock:index' %}" class="nav-link px-2 text-muted">主页</a></li>
                    <li class="nav-item"><a href="{% url 'rock:all_photos' %}" class="nav-link px-2 text-muted">所有照片</a>
                    </li>
                    <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">XXX</a></li>
                    <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">XXX</a></li>
                    <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">关于</a></li>
                </ul>
                <p class="text-center text-muted">&copy; 2023 Zjx.</p>
            </footer>
        </div>
    </footer>

    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    {% block script %}{% endblock%}

</body>

</html>

rock/templates/mine_detail.html
{% extends "base_generic.html" %}

{% block static %}
{% load static %}
{% endblock%}

{% block title %}岩井详情{% endblock %}

{% block content %}

<div class="container-fluid overflow-hidden">
    <div class="row g-5 py-4">
        <div class="col-md-4 col-lg-3 bg-light">
            <h4 class="d-flex justify-content-between align-items-center mb-3">
                <span class="text-primary">岩井详情</span>
            </h4>
            <ul class="list-group list-group-flush mb-3 rounded">
                <li class="list-group-item d-flex justify-content-between lh-sm">
                    <div>
                        <h6 class="my-0">井号</h6>
                        <small class="text-muted">well number</small>
                    </div>
                    <span class="text-muted">{{ mine.name }}</span>
                </li>
                <li class="list-group-item d-flex justify-content-between lh-sm">
                    <div>
                        <h6 class="my-0">地区</h6>
                        <small class="text-muted">region</small>
                    </div>
                    <span class="text-muted">{{ mine.region }}</span>
                </li>
                <li class="list-group-item d-flex justify-content-between lh-sm">
                    <div>
                        <h6 class="my-0">井深</h6>
                        <small class="text-muted">well depth</small>
                    </div>
                    <span class="text-muted">{{ mine.max_depth }}m</span>
                </li>
                <li class="list-group-item d-flex justify-content-between lh-sm">
                    <div>
                        <h6 class="my-0">照片总数</h6>
                        <small class="text-muted">total number of photos</small>
                    </div>
                    <span class="text-muted">{{ mine.pic_num }}</span>
                </li>
                <li class="list-group-item d-flex justify-content-between lh-sm">
                    <div>
                        <h6 class="my-0">样本总数</h6>
                        <small class="text-muted">total number of samples</small>
                    </div>
                    <span class="text-muted">{{ mine.sample_num }}</span>
                </li>
            </ul>
        </div>
        <div class="col-md-8 col-lg-9">
            <div class="row">
                <div class="col-12">
                    <h4 class="d-flex justify-content-between align-items-center">
                        <span class="text-primary">地层分层</span>
                    </h4>
                    <div id="layer_chart" class=""></div>
                </div>
                <div class="col-12">
                    <h4 class="d-flex justify-content-between align-items-center">
                        <span class="text-primary">样品定名</span>
                    </h4>
                    <div id="sample_name_chart"></div>
                </div>
                <div class="col-12">
                    <h4 class="d-flex justify-content-between align-items-center">
                        <span class="text-primary">岩石成分</span>
                    </h4>
                    <div id="rock_composition_chart"></div>
                </div>
            </div>
        </div>
    </div>
</div>

{% block script %}
<script src="{% static './frontend/minedetail.js' %}"></script>
{% endblock%}

{% endblock %}

rock/templates/rock_detail.html
{% extends "base_generic.html" %}

{% block static %}
{% load static %}
<link rel="stylesheet" href="{% static 'node_modules/viewerjs/dist/viewer.min.css' %}">
{% endblock%}

{% block title %}薄片详情{% endblock %}

{% block content %}
<div class="container-fluid overflow-hidden">
    <div class="row g-5 py-4 bg-light">
        <div class="col-md-7 col-lg-8">
            <img id="rock_photo" class="img-fluid rounded" src="{{ pic.image.url }}" style="cursor: pointer;">
        </div>
        <div class="col-md-5 col-lg-4">
            <h4 class="d-flex justify-content-between align-items-center mb-3">
                <span class="text-primary">薄片详情</span>
            </h4>
            <ul class="list-group list-group-flush mb-3 rounded">
                <li class="list-group-item d-flex justify-content-between lh-sm">
                    <div>
                        <h6 class="my-0">地区</h6>
                        <small class="text-muted">region</small>
                    </div>
                    <span class="text-muted">{{ pic.mine_num.region }}</span>
                </li>
                <li class="list-group-item d-flex justify-content-between lh-sm">
                    <div>
                        <h6 class="my-0">井号</h6>
                        <small class="text-muted">well number</small>
                    </div>
                    <span class="text-muted">{{ pic.mine_num.name }}</span>
                </li>
                <li class="list-group-item d-flex justify-content-between lh-sm">
                    <div>
                        <h6 class="my-0">井深</h6>
                        <small class="text-muted">well depth</small>
                    </div>
                    <span class="text-muted">{{ pic.depth }}m</span>
                </li>
                <li class="list-group-item d-flex justify-content-between lh-sm">
                    <div>
                        <h6 class="my-0">物镜倍数</h6>
                        <small class="text-muted">objective multiple</small>
                    </div>
                    <span class="text-muted">{{ pic.lens_mul }}X</span>
                </li>
                <li class="list-group-item d-flex justify-content-between lh-sm">
                    <div>
                        <h6 class="my-0">正交偏光</h6>
                        <small class="text-muted">orthogonality</small>
                    </div>
                    <span class="text-muted">{{ pic.get_orth }}</span>
                </li>
            </ul>
        </div>
    </div>
</div>

{% block script %}
<script src="{% static 'node_modules/viewerjs/dist/viewer.min.js' %}"></script>
<script>
    const image = document.getElementById('rock_photo');
    const viewer = new Viewer(image);
</script>
{% endblock%}

{% endblock %}

rock/templates/upload_images.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
</head>

<body>
    <h1>Upload Images</h1>
    <p>Current user: {{ user }}</p>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Upload Images</button>
    </form>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
    </ul>
    {% endif %}
</body>

</html>